---
title: "Final Project PPT"
author: "Longhao Chen"
date: "11/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(officer)
library(magrittr)
library(tidyverse)
library(readxl)
library(rvg)
#General Set up
temp <- read_pptx("Template.pptx") 
layout_summary(temp)
master <- "Gallery"
layout_properties(x = temp, layout = "Title Slide", master = master )

#First slide with title

temp %<>%  add_slide(layout = "Title Slide", master = master) %>% 
  ph_with_text(type = "ctrTitle", str = "Benford analysis on aviation statistics") %>% 
  ph_with_text(type =  "dt", str = format(Sys.Date())) %>% 
  ph_with_text(type="subTitle", str="Tell me the fishy data!")

#Second slide with text

temp %<>%  add_slide(layout = "Two Content", master = master  ) %>% 
  ph_with_text(type = "title", str = "What is Benford's law?") %>% 
  ph_with_ul(type = "body", index = 2, 
               str_list = c("1. Benford's law is a phenomenological law also called the first digit law.", 
                            "2. Digit 1 tends to occur with probability of 30%, greater than the expected of 11%"),
               level_list = c(1,1)) %>%
  ph_with_img_at( src = "benford.png", width = 4, height = 3, left = 7, top = 2.2)

#Third slide

temp %<>% add_slide(layout = "Title and Content", master = master ) %>% 
  ph_with_text(type = "title", str = "What is the distribution of top 10 airlines?") %>% 
  ph_with_text(type = "body", str = "We can see that out of top 10 airlines, top 3 airline companies have numbers begin with 1. Is this a coincidence or not?")%>%
  ph_with_img_at( src = "top10.jpg", width = 7, height = 4, left = 4, top = 3)


#Fourth slide
temp %<>% add_slide(layout = "Two Content", master = master ) %>% 
  ph_with_text(type = "title", str = "Let's look at what Benford's analysis?") %>% 
  ph_with_ul(type = "body", index = 2, 
               str_list = c("1. Overall the data follows the distribution of Benford's law pretty well as we can see that the dashed red line matches with the black bar plot.", 
                            
                            "2. There are some spikes on different region especially on 1. This is probably due to the fact that our dataframe is only consisted of three years data."),
               level_list = c(1,1)) %>%
  ph_with_img_at( src = "benford1.jpg", width = 5, height = 4, left = 7, top = 2.2)

#Fifth
temp %<>% add_slide(layout = "Title and Content", master = master ) %>% 
  ph_with_text(type = "title", str = "suspicious airlines using Benford analysis") %>% 
  ph_with_img( src = "top5sus.jpg")

#Sixth
temp %<>% add_slide(layout = "Title and Content", master = master ) %>% 
  ph_with_text(type = "title", str = "suspicious airlines using Benford analysis") %>% ph_with_text(type = "body", str = "If you are careful enough, you will find out those suspicious airline companies have a 0 sum airtime but non zero entry for other columns! Wow. Benford's analysis find these suspicious data so quickly. We have some confidence to say that those airlines 'lie about' their air time. How does this happen? Probably because the data is not recorded in the system!")

#Seventh
temp %<>% add_slide(layout = "Title and Content", master = master ) %>% 
  ph_with_text(type = "title", str = "Thanks for watching") %>% ph_with_text(type = "body", str = "Any questions? Feel free to email me at lc18@bu.edu")
  
  remove_slide(temp, index = 1)

print(temp, target = "Benford's law.pptx") 
```


